# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 05:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import husky.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=4000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, max_length=65000, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_of_event', models.DateTimeField()),
                ('duration', models.CharField(blank=True, max_length=25, null=True, verbose_name=b'Duration (ie. 1 hour)')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, max_length=65000, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.CharField(default=b'_sponsor_@huskyhustle.com', max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('donation', husky.models.CurrencyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('donated', husky.models.CurrencyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('per_lap', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=0)),
                ('paid_by', models.CharField(blank=True, choices=[(b'cash', b'cash'), (b'check', b'check'), (b'online', b'online')], default=b'online', max_length=6, null=True)),
                ('type', models.IntegerField(choices=[(0, b'student'), (1, b'teacher'), (2, b'principal')], default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=255)),
                ('shorten', models.CharField(max_length=255)),
                ('status', models.IntegerField(blank=True, choices=[(0, 0), (1, 1)], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=4000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(default=None, max_length=100)),
                ('api_key', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('api_secret', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('client_id', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('business_id', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('public_cert', models.TextField(blank=True, default=None, max_length=65000, null=True)),
                ('public_key', models.TextField(blank=True, default=None, max_length=65000, null=True)),
                ('private_key', models.TextField(blank=True, default=None, max_length=65000, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(default=b'_sponsor_@huskyhustle.com', max_length=100)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='husky.Donation')),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, choices=[(1, b'Child'), (2, b'Adult')], null=True)),
                ('size', models.IntegerField(blank=True, choices=[(1, b'XS (2-4)'), (2, b'S (6-8)'), (3, b'M (10-12)'), (4, b'L (14-16)'), (5, b'XL (Adult Small)'), (6, b'S'), (7, b'M'), (8, b'L'), (9, b'XL'), (10, b'XXL')], null=True)),
                ('price', husky.models.CurrencyField(blank=True, decimal_places=2, default=10.0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShirtOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(default=b'_sponsor_@huskyhustle.com', max_length=100)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', husky.models.CurrencyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid', models.BooleanField(default=0)),
                ('paid_by', models.CharField(blank=True, choices=[(b'cash', b'cash'), (b'check', b'check'), (b'online', b'online')], default=b'online', max_length=6, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('shirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shirtorders', to='husky.Shirt')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('laps', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[(b'M', b'Boy'), (b'F', b'Girl')], max_length=1, null=True)),
                ('collected', husky.models.CurrencyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disqualify', models.IntegerField(choices=[(0, b'No'), (1, b'Yes')], default=0)),
                ('pledged', husky.models.CurrencyField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'teacher'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[(b'Mrs.', b'Mrs.'), (b'Ms.', b'Ms.'), (b'Miss', b'Miss'), (b'Mr.', b'Mr.')], default=b'Mrs.', max_length=5)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, default=b'(714) 734-1878', max_length=25, null=True)),
                ('room_number', models.CharField(max_length=5)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('shorten', models.CharField(blank=True, max_length=255, null=True)),
                ('list_type', models.IntegerField(blank=True, null=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='husky.Grade')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='husky.Teacher'),
        ),
        migrations.AddField(
            model_name='shirtorder',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='husky.Student'),
        ),
        migrations.AddField(
            model_name='donation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='husky.Student'),
        ),
    ]
